### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by kn007** [marknote/TeleShellBot#3]
```
[bot.plugin] loaded 'regExpMessage' plugin
[bot.plugin] loaded 'shortReply' plugin
[bot.info] bot started
args:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /help ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

node version: v6.11.3

**Comment by marknote** [comment]
Thanks for reporting the issue.
Error handling has been added. Please check again.

**Comment by kn007** [comment]
It's working now.
