### ISSUE TITLE
Invalid bot token

### ISSUE THREAD

**Issue by kevinzhang1234** [marknote/TeleShellBot#4]
/root/TeleShellBot/node_modules/telebot/lib/telebot.js:16
            throw Error('[bot.error] invalid bot token');
            ^

Error: [bot.error] invalid bot token
    at new TeleBot (/root/TeleShellBot/node_modules/telebot/lib/telebot.js:16:19)
    at Object.<anonymous> (/root/TeleShellBot/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Is this due to a password error?

**Comment by marknote** [comment]
you can chat with `@BotFather` to get the token 
then put it in `config.js` file

```js
module.exports = {
    config: function(){
        return (
            {
                adminUsers:[XXXXX], //admin users' telegram id, should be numbers
                botToken: '55555555:AAAAAAAAAAA', // bot token
            }
        );
    }
};
```
